// Loading Actions
export const APP_DATA_LOADING_TRUE = "APP_DATA_LOADING_TRUE";
export const APP_DATA_LOADING_FALSE = "APP_DATA_LOADING_FALSE";

// Burgers Actions
export const FETCH_BURGERS = 'FETCH_BURGERS';
export const FETCH_BURGERS_SUCCESS = 'FETCH_BURGERS_SUCCESS';
export const FETCH_BURGERS_ERROR = 'FETCH_BURGERS_ERROR';
export const UPDATE_BURGERS = 'UPDATE_BURGERS';
export const DELETE_BURGERS = 'DELETE_BURGERS';
export const CREATE_BURGERS = 'CREATE_BURGERS';

// Schedule Actions
export const FETCH_SCHEDULE = 'FETCH_SCHEDULE';
export const FETCH_SCHEDULE_SUCCESS = 'FETCH_SCHEDULE_SUCCESS';
export const FETCH_SCHEDULE_ERROR = 'FETCH_SCHEDULE_ERROR';
export const UPDATE_SCHEDULE = 'UPDATE_SCHEDULE';
export const DELETE_SCHEDULE = 'DELETE_SCHEDULE';
export const CREATE_SCHEDULE = 'CREATE_BURGERS';

// Users Actions
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';
export const UPDATE_USERS = 'UPDATE_USERS';
export const DELETE_USERS = 'DELETE_USERS';
export const CREATE_USERS = 'CREATE_USERS';